/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimeDetails: typeof import('./src/components/anime/AnimeDetails.vue')['default']
    AnimeForm: typeof import('./src/components/anime/AnimeForm.vue')['default']
    AnimeFormSearch: typeof import('./src/components/anime/AnimeFormSearch.vue')['default']
    GeneralCard: typeof import('./src/components/shared/GeneralCard.vue')['default']
    InluneInput: typeof import('./src/components/shared/InluneInput.vue')['default']
    InputModal: typeof import('./src/components/shared/InputModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
